apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  # Temporalmente apunta al servicio interno (para pruebas)
  api_base: "https://p5zd4xx8te.execute-api.us-east-1.amazonaws.com/prod" # Debe apuntar a la URL del API Gateway en la version final (despu√©s de crear el LoadBalancer y API Gateway)